import { CanvasElement, EditorModes, SlideExample } from "@/interfaces";
import { Participant } from "@/interfaces/Participants";

export const initialState = {
  editorMode: "cursor" as EditorModes,
  presentationCreator: "",
  presentationId: "",
  presentationTopic: "",
  currentSlide: 1,
  totalSlides: 10,
  role: "viewer" as string,
  isLoading: true,
  startX: 0,
  startY: 0,
  isDrawing: false,
  slidesPreviews: [] as SlideExample[],
  drawnElements: [] as CanvasElement[],
  deletedElements: [] as CanvasElement[],
  isDropDownMenuOpen: false,
  dropDownMenuX: 100,
  dropDownMenuY: 100,
  clickedCanvasElement: {} as CanvasElement | null,
  selectedStrokeColor: "#00FFFF",
  modifiedElement: {} as CanvasElement | null,
  isEditing: false,
  textFieldX: 0,
  textFieldY: 0,
  editedTextElement: {} as CanvasElement | null,
  textFieldValue: "",
  previousElements: "",
  slideMenuX: 0,
  slideMenuY: 0,
  isSlideMenuOpen: false,
  clikedSlideId: "",
  participants: [] as Participant[],
  participanName: "",
  scale: 1,
};
